schema_version = "1.0.0"

id = "uv_maps_plus"
name = "UV Maps+"
version = "1.0.4"
tagline = "Reorder UV Maps, Copy/Paste UVs, and exceed the 8-map limit"
maintainer = "JR3DFUL"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["UV", "User Interface"]
