schema_version = "1.0.0"

id = "uv_maps_plus"
name = "UV Maps+"
version = "1.0.0"
tagline = "Manage more than 8 UV maps via the attribute system"
maintainer = "JR3DFUL"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["UV"]
